apiVersion: v1 # Secret has to be created before using them in deployment
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # default key value secret type
data: #only stores value in base64 format. In terminal > echo -n 'your_value' | base64
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
